DROP TABLE "TB_MEMBER";

CREATE TABLE "TB_MEMBER" (
   "DEV_NO"   NUMBER      NOT NULL,
   "DEV_ID"   VARCHAR(20)      NOT NULL,
   "DEV_PW"   VARCHAR(30)      NOT NULL,
   "DEV_NM"   VARCHAR(30)      NOT NULL,
   "PHONE"   VARCHAR(14)      NOT NULL,
   "EMAIL"   VARCHAR(30)      NOT NULL,
   "CAREER"   NUMBER   DEFAULT 0   NULL,
   "SPEC"   VARCHAR2(3000)      NULL,
   "DEV_YN"   CHAR(1)      NOT NULL,
   "SCSN_FL"   CHAR(1)   DEFAULT 'N'   NULL
);

COMMENT ON COLUMN "TB_MEMBER"."DEV_NO" IS '회원번호(PK)';

COMMENT ON COLUMN "TB_MEMBER"."DEV_ID" IS '회원아이디';

COMMENT ON COLUMN "TB_MEMBER"."DEV_PW" IS '비밀번호';

COMMENT ON COLUMN "TB_MEMBER"."DEV_NM" IS '회원 이름';

COMMENT ON COLUMN "TB_MEMBER"."PHONE" IS '회원 전화번호';

COMMENT ON COLUMN "TB_MEMBER"."EMAIL" IS '회원 이메일';

COMMENT ON COLUMN "TB_MEMBER"."CAREER" IS '회원 경력';

COMMENT ON COLUMN "TB_MEMBER"."SPEC" IS '회원 사용 기술';

COMMENT ON COLUMN "TB_MEMBER"."DEV_YN" IS '개발자 여부 확인';

COMMENT ON COLUMN "TB_MEMBER"."SCSN_FL" IS '회원 탈퇴 여부';

DROP TABLE "TB_COMPANY";

CREATE TABLE "TB_COMPANY" (
   "COM_NO"   NUMBER      NOT NULL,
   "COM_NM"   VARCHAR(30)      NOT NULL,
   "PHONE"   VARCHAR(14)      NOT NULL,
   "EMAIL"   VARCHAR(30)      NOT NULL,
   "COMMENT"   VARCHAR2(3000)      NULL,
   "DEV_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "TB_COMPANY"."COM_NO" IS '회사번호(PK)';

COMMENT ON COLUMN "TB_COMPANY"."COM_NM" IS '회사명';

COMMENT ON COLUMN "TB_COMPANY"."PHONE" IS '회사 전화번호';

COMMENT ON COLUMN "TB_COMPANY"."EMAIL" IS '회원 주소';

COMMENT ON COLUMN "TB_COMPANY"."COMMENT" IS '회사 소개글';

COMMENT ON COLUMN "TB_COMPANY"."DEV_NO" IS '회원번호(PK)';

DROP TABLE "TB_OFFER";

CREATE TABLE "TB_OFFER" (
   "JO_NO"   NUMBER      NOT NULL,
   "LOCATION"   VARCHAR(30)      NOT NULL,
   "SAL"   NUMBER      NOT NULL,
   "TERM"   NUMBER      NOT NULL,
   "JOB"   VARCHAR(300)      NOT NULL,
   "COM_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "TB_OFFER"."JO_NO" IS '구직정보 번호(PK)';

COMMENT ON COLUMN "TB_OFFER"."LOCATION" IS '근무 지역';

COMMENT ON COLUMN "TB_OFFER"."SAL" IS '급여(만원)';

COMMENT ON COLUMN "TB_OFFER"."TERM" IS '계약기간(월)';

COMMENT ON COLUMN "TB_OFFER"."JOB" IS '업무내용';

COMMENT ON COLUMN "TB_OFFER"."COM_NO" IS '회사번호(PK)';

DROP TABLE "TB_REVIEW";

CREATE TABLE "TB_REVIEW" (
   "REVW_NO"   NUMBER      NOT NULL,
   "TITLE"   VARCHAR2(300)      NOT NULL,
   "CONTENT"   VARCHAR2(3000)      NOT NULL,
   "CREATE_AT"   DATE   DEFAULT SYSDATE   NOT NULL,
   "CATEGORY"   CHAR(3)      NOT NULL,
   "DEV_NO"   NUMBER      NOT NULL
);

COMMENT ON COLUMN "TB_REVIEW"."REVW_NO" IS '후기 번호(PK)';

COMMENT ON COLUMN "TB_REVIEW"."TITLE" IS '후기 제목';

COMMENT ON COLUMN "TB_REVIEW"."CONTENT" IS '후기 내용';

COMMENT ON COLUMN "TB_REVIEW"."CREATE_AT" IS '작성일';

COMMENT ON COLUMN "TB_REVIEW"."CATEGORY" IS '작성 회원 타입';

COMMENT ON COLUMN "TB_REVIEW"."DEV_NO" IS '회원번호(PK)';

ALTER TABLE "TB_MEMBER" ADD CONSTRAINT "PK_TB_MEMBER" PRIMARY KEY (
   "DEV_NO"
);

ALTER TABLE "TB_COMPANY" ADD CONSTRAINT "PK_TB_COMPANY" PRIMARY KEY (
   "COM_NO"
);

ALTER TABLE "TB_OFFER" ADD CONSTRAINT "PK_TB_OFFER" PRIMARY KEY (
   "JO_NO"
);

ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "PK_TB_REVIEW" PRIMARY KEY (
   "REVW_NO"
);

ALTER TABLE "TB_COMPANY" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_COMPANY_1" FOREIGN KEY (
   "DEV_NO"
)
REFERENCES "TB_MEMBER" (
   "DEV_NO"
);

ALTER TABLE "TB_OFFER" ADD CONSTRAINT "FK_TB_COMPANY_TO_TB_OFFER_1" FOREIGN KEY (
   "COM_NO"
)
REFERENCES "TB_COMPANY" (
   "COM_NO"
);

ALTER TABLE "TB_REVIEW" ADD CONSTRAINT "FK_TB_MEMBER_TO_TB_REVIEW_1" FOREIGN KEY (
   "DEV_NO"
)
REFERENCES "TB_MEMBER" (
   "DEV_NO"
);

----------------------------------------------------------------

ALTER TABLE TB_MEMBER
ADD CONSTRAINT CK_DEV_YN CHECK(DEV_YN IN('Y', 'N'));

ALTER TABLE TB_MEMBER
ADD CONSTRAINT CK_SCSN_FL CHECK(SCSN_FL IN('Y', 'N'));

ALTER TABLE TB_REVIEW
ADD CONSTRAINT CK_CATEGORY CHECK(CATEGORY IN('DEV', 'COM'));

ALTER TABLE TB_MEMBER
RENAME COLUMN DEV_NM TO MEM_NM;

ALTER TABLE TB_COMPANY
RENAME COLUMN DEV_NO TO MEM_NO;

CREATE SEQUENCE SEQ_OFF;

ALTER TABLE TB_OFFER
ADD O_SCSN_FL CHAR(1) DEFAULT 'N' NOT NULL;

ALTER TABLE TB_OFFER
ADD CONSTRAINT CK_O_SCSN_FL CHECK(O_SCSN_FL IN('Y', 'N'));

CREATE OR REPLACE VIEW OFFER_COM AS
SELECT JO_NO, COM_NM, LOCATION, SAL, TERM, JOB, COM_NO
FROM TB_OFFER
JOIN TB_COMPANY USING(COM_NO)
WHERE O_SCSN_FL = 'N';

COMMIT;

CREATE OR REPLACE VIEW V_REVIEW AS
SELECT REVW_NO, MEM_NM, TITLE, CONTENT, CREATE_AT
FROM TB_REVIEW
JOIN TB_MEMBER USING(MEM_NO)
WHERE DEV_YN = 'Y';

ALTER TABLE TB_REVIEW
DROP COLUMN CATEGORY;